import { Solicitud } from '@/types/ipas';

export const mockSolicitudes: Solicitud[] = [
  // AUDITORIA EN SALUD COHORTE 52
  {
    id: 'REQ-AUD52-01',
    nombrePrograma: 'Auditoría en Salud - Cohorte 52',
    estudiantes: 12,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Freddy Gómez',
    fechaInicioDocente: '2026-08-14',
    fechaFinDocente: '2026-08-15',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 80,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-AUD52-02',
    nombrePrograma: 'Auditoría en Salud - Cohorte 52',
    estudiantes: 12,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Local',
    fechaInicioDocente: '2026-09-04',
    fechaFinDocente: '2026-09-05',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 80,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // AUDITORIA EN SALUD COHORTE 51
  {
    id: 'REQ-AUD51-01',
    nombrePrograma: 'Auditoría en Salud - Cohorte 51',
    estudiantes: 15,
    reqProyector: true,
    reqStreaming: true,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Titular',
    fechaInicioDocente: '2026-08-21',
    fechaFinDocente: '2026-08-22',
    modalidadDocente: 'Híbrida',
    franjaHorariaPuntos: 70,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // DIPLOMADO FINANZAS AVANZADAS
  {
    id: 'REQ-DFA-01',
    nombrePrograma: 'Diplomado Finanzas Avanzadas',
    estudiantes: 25,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: true,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Experto Financiero 1',
    fechaInicioDocente: '2026-09-11',
    fechaFinDocente: '2026-09-12',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 50,
    nivelFormacion: 'Diplomado',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-DFA-02',
    nombrePrograma: 'Diplomado Finanzas Avanzadas',
    estudiantes: 25,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: true,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Experto Financiero 2',
    fechaInicioDocente: '2026-10-16',
    fechaFinDocente: '2026-10-17',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 50,
    nivelFormacion: 'Diplomado',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // ESP EN FINANZAS 2026 COHORTE 52
  {
    id: 'REQ-FIN52-01',
    nombrePrograma: 'Especialización Finanzas - Cohorte 52',
    estudiantes: 30,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: true,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Finanzas A',
    fechaInicioDocente: '2026-08-07',
    fechaFinDocente: '2026-08-08',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 90,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-FIN52-02',
    nombrePrograma: 'Especialización Finanzas - Cohorte 52',
    estudiantes: 30,
    reqProyector: true,
    reqStreaming: true,
    reqSoftware: true,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Finanzas B',
    fechaInicioDocente: '2026-09-18',
    fechaFinDocente: '2026-09-19',
    modalidadDocente: 'Híbrida',
    franjaHorariaPuntos: 90,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // ESP EN FINANZAS 2026 COHORTE 53
  {
    id: 'REQ-FIN53-01',
    nombrePrograma: 'Especialización Finanzas - Cohorte 53',
    estudiantes: 28,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: true,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Docente Invitado Bogotá',
    fechaInicioDocente: '2026-08-28',
    fechaFinDocente: '2026-08-29',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 90,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: true,
    tipoAccesibilidad: 'Movilidad reducida',
  },

  // DIPLOMADO FINANZAS COHORTE 20
  {
    id: 'REQ-DIPFIN20-01',
    nombrePrograma: 'Diplomado Finanzas Cohorte 20',
    estudiantes: 18,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Dip 20',
    fechaInicioDocente: '2026-11-06',
    fechaFinDocente: '2026-11-07',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 40,
    nivelFormacion: 'Diplomado',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // GERENCIA EN SALUD COHORTE 48
  {
    id: 'REQ-GERSAL48-01',
    nombrePrograma: 'Gerencia en Salud - Cohorte 48',
    estudiantes: 22,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Experto Salud Pública',
    fechaInicioDocente: '2026-08-14',
    fechaFinDocente: '2026-08-15',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 75,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-GERSAL48-02',
    nombrePrograma: 'Gerencia en Salud - Cohorte 48',
    estudiantes: 22,
    reqProyector: true,
    reqStreaming: true,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Local Salud',
    fechaInicioDocente: '2026-10-02',
    fechaFinDocente: '2026-10-03',
    modalidadDocente: 'Híbrida',
    franjaHorariaPuntos: 75,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // GERENCIA EN SALUD COHORTE 49
  {
    id: 'REQ-GERSAL49-01',
    nombrePrograma: 'Gerencia en Salud - Cohorte 49',
    estudiantes: 20,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Gerencia',
    fechaInicioDocente: '2026-09-11',
    fechaFinDocente: '2026-09-12',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 75,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // DIPLOMADO GESTION GERENCIAL 33
  {
    id: 'REQ-DIPGES33-01',
    nombrePrograma: 'Diplomado Gestión Gerencial 33',
    estudiantes: 35,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Conferencista Medellín',
    fechaInicioDocente: '2026-10-23',
    fechaFinDocente: '2026-10-24',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 40,
    nivelFormacion: 'Diplomado',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // ESP EN GESTION GERENCIAL 49
  {
    id: 'REQ-GESGER49-01',
    nombrePrograma: 'Especialización Gestión Gerencial - Cohorte 49',
    estudiantes: 38,
    reqProyector: true,
    reqStreaming: true,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente G.G. 1',
    fechaInicioDocente: '2026-08-21',
    fechaFinDocente: '2026-08-22',
    modalidadDocente: 'Híbrida',
    franjaHorariaPuntos: 85,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: true,
    tipoAccesibilidad: 'Visual',
  },
  {
    id: 'REQ-GESGER49-02',
    nombrePrograma: 'Especialización Gestión Gerencial - Cohorte 49',
    estudiantes: 38,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente G.G. 2',
    fechaInicioDocente: '2026-11-20',
    fechaFinDocente: '2026-11-21',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 85,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: true,
    tipoAccesibilidad: 'Visual',
  },

  // MAESTRÍA EN G O COHORTE 11
  {
    id: 'REQ-MGO11-01',
    nombrePrograma: 'Maestría en Gestión de Organizaciones - Cohorte 11',
    estudiantes: 15,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: true,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Investigador Internacional',
    fechaInicioDocente: '2026-09-04',
    fechaFinDocente: '2026-09-05',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 100,
    nivelFormacion: 'Maestría',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-MGO11-02',
    nombrePrograma: 'Maestría en Gestión de Organizaciones - Cohorte 11',
    estudiantes: 15,
    reqProyector: true,
    reqStreaming: true,
    reqSoftware: true,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Docente Maestría Local',
    fechaInicioDocente: '2026-10-30',
    fechaFinDocente: '2026-10-31',
    modalidadDocente: 'Híbrida',
    franjaHorariaPuntos: 100,
    nivelFormacion: 'Maestría',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // ESP EN REVISORIA FISCAL (De los datos extraídos)
  {
    id: 'REQ-REV-01',
    nombrePrograma: 'Especialización Revisoría Fiscal - Cohorte 11',
    estudiantes: 20,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Daniel Hurtado Cabrera (Bogotá)',
    fechaInicioDocente: '2026-10-03',
    fechaFinDocente: '2026-10-04',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 80,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-REV-02',
    nombrePrograma: 'Especialización Revisoría Fiscal - Cohorte 11',
    estudiantes: 20,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Carlos Cantillo Puello',
    fechaInicioDocente: '2026-10-17',
    fechaFinDocente: '2026-10-18',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 80,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-REV-03',
    nombrePrograma: 'Especialización Revisoría Fiscal - Cohorte 11',
    estudiantes: 20,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Orlando Arrieta Díaz',
    fechaInicioDocente: '2026-10-31',
    fechaFinDocente: '2026-11-01',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 80,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-REV-04',
    nombrePrograma: 'Especialización Revisoría Fiscal - Cohorte 11',
    estudiantes: 20,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Juan Carlos Hernandez Muñoz',
    fechaInicioDocente: '2026-11-21',
    fechaFinDocente: '2026-11-22',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 80,
    nivelFormacion: 'Especialización',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },

  // MDTGP COHORTE 4 Y 5 (Maestría en Desarrollo Territorial)
  {
    id: 'REQ-MDTGP-01',
    nombrePrograma: 'Maestría Desarrollo Territorial - Cohorte 4 y 5',
    estudiantes: 40,
    reqProyector: true,
    reqStreaming: true,
    reqSoftware: false,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'José Morelos Gómez',
    fechaInicioDocente: '2026-08-07',
    fechaFinDocente: '2026-08-08',
    modalidadDocente: 'Híbrida',
    franjaHorariaPuntos: 100,
    nivelFormacion: 'Maestría',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-MDTGP-02',
    nombrePrograma: 'Maestría Desarrollo Territorial - Cohorte 4 y 5',
    estudiantes: 40,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: true,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Juan Carlos Vergara - Rosario Blanco',
    fechaInicioDocente: '2026-09-18',
    fechaFinDocente: '2026-09-19',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 100,
    nivelFormacion: 'Maestría',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-MDTGP-03',
    nombrePrograma: 'Maestría Desarrollo Territorial - Cohorte 4 y 5',
    estudiantes: 40,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: false,
    tieneDocenteInvitado: true,
    docenteForaneoPuntos: 100,
    docenteId: 'Orlando Deavila - Lewis León',
    fechaInicioDocente: '2026-10-16',
    fechaFinDocente: '2026-10-17',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 100,
    nivelFormacion: 'Maestría',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
  {
    id: 'REQ-MDTGP-04',
    nombrePrograma: 'Maestría Desarrollo Territorial - Cohorte 4 y 5',
    estudiantes: 40,
    reqProyector: true,
    reqStreaming: false,
    reqSoftware: true,
    tieneDocenteInvitado: false,
    docenteForaneoPuntos: 0,
    docenteId: 'Asesor Trabajo Grado',
    fechaInicioDocente: '2026-11-20',
    fechaFinDocente: '2026-11-21',
    modalidadDocente: 'Presencial',
    franjaHorariaPuntos: 100,
    nivelFormacion: 'Maestría',
    reqAccesibilidad: false,
    tipoAccesibilidad: 'Ninguna',
  },
];

export const solicitudesData = process.env.NODE_ENV === 'production' && process.env.STATIC_EXPORT !== 'true' 
  ? [] 
  : mockSolicitudes;
