import { 
  AbsoluteFill, 
  Sequence, 
  Audio, 
  Video,
  OffthreadVideo, 
  staticFile, 
  useCurrentFrame, 
  interpolate, 
  useVideoConfig,
  spring,
  Img,
  interpolateColors,
  Easing
} from 'remotion';

// Import timing manifest generated by Gemini 3.8 Flash TTS
import timings from '../public/audio/voice_timings.json';

interface ActConfig {
  id: string;
  actNumber: string;
  badgeTitle: string;
  subtitle: string;
  videoClip: string;
  audioFile: string;
  scaleStart?: number;
  scaleEnd?: number;
  yStart?: number;
  yEnd?: number;
  cameraMove?: {
    startFrame: number;
    targetScale: number;
    targetX: number;
    targetY: number;
  };
  startFromFrames?: number;
  sfx?: { type: 'swoosh' | 'click' | 'typing'; frame: number }[];
}

const ACT_CONFIGS: Record<string, ActConfig> = {
  act1: {
    id: 'act1',
    actNumber: '01',
    badgeTitle: 'Apertura Institucional',
    subtitle: 'La Evolución de la Educación Continua',
    videoClip: 'assets/clips/full_recording_cfr.mp4',
    audioFile: 'audio/posgrados_act1.mp3',
    startFromFrames: 0,
    scaleStart: 1.05,
    scaleEnd: 1.15,
    yStart: 0,
    yEnd: -40,
    sfx: [{ type: 'swoosh', frame: 120 }],
  },
  act2: {
    id: 'act2',
    actNumber: '02',
    badgeTitle: 'Catálogo Dinámico',
    subtitle: '124 Cursos Modulares en Tiempo Real',
    videoClip: 'assets/clips/full_recording_cfr.mp4',
    audioFile: 'audio/posgrados_act2.mp3',
    startFromFrames: 750,
    cameraMove: { startFrame: 90, targetScale: 1.15, targetX: 0, targetY: 20 },
    sfx: [{ type: 'swoosh', frame: 90 }, { type: 'click', frame: 150 }],
  },
  act3: {
    id: 'act3',
    actNumber: '03',
    badgeTitle: 'Ficha Técnica e Interactividad',
    subtitle: 'Navegación Intuitiva y Detallada',
    videoClip: 'assets/clips/full_recording_cfr.mp4',
    audioFile: 'audio/posgrados_act3.mp3',
    startFromFrames: 1050,
    cameraMove: { startFrame: 150, targetScale: 1.2, targetX: -20, targetY: 40 },
    sfx: [{ type: 'swoosh', frame: 140 }, { type: 'click', frame: 220 }],
  },
  act4: {
    id: 'act4',
    actNumber: '04',
    badgeTitle: 'Pasarela de Pagos Inmediata',
    subtitle: 'Integración Webhook Menor a 2 Segundos',
    videoClip: 'assets/clips/full_recording_cfr.mp4',
    audioFile: 'audio/posgrados_act4.mp3',
    startFromFrames: 7200,
    cameraMove: { startFrame: 180, targetScale: 1.25, targetX: 0, targetY: -10 },
    sfx: [{ type: 'swoosh', frame: 170 }, { type: 'click', frame: 250 }],
  },
  act5: {
    id: 'act5',
    actNumber: '05',
    badgeTitle: 'UdeC Empresas B2B',
    subtitle: 'Bolsas de Crédito y Portal Corporativo',
    videoClip: 'assets/clips/full_recording_cfr.mp4',
    audioFile: 'audio/posgrados_act5.mp3',
    startFromFrames: 4350,
    cameraMove: { startFrame: 200, targetScale: 1.15, targetX: 0, targetY: 0 },
    sfx: [{ type: 'swoosh', frame: 190 }, { type: 'click', frame: 260 }],
  }
};

export const VideoInstitucionalPosgrados: React.FC = () => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  // Global presentation progress (0 to 1)
  const globalProgress = interpolate(frame, [0, durationInFrames], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });

  return (
    <AbsoluteFill 
      style={{ 
        backgroundColor: '#000000', // Pure Apple-style black
        color: '#F8FAFC', 
        fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' 
      }}
    >
      
      {/* ─── ACT SEQUENCES WITH GEMINI 3.8 FLASH TTS & REAL PLATFORM VIDEO ─── */}
      {Object.entries((timings as any).acts).map(([actKey, actData]: [string, any]) => {
        const config = ACT_CONFIGS[actKey] || ACT_CONFIGS.act1;

        return (
          <Sequence
            key={actKey}
            from={actData.startFrame}
            durationInFrames={actData.durationFrames}
          >
            <ExecutiveActView 
              actData={actData} 
              config={config} 
            />
            <ActAudio actData={actData} />
          </Sequence>
        );
      })}

      {/* ─── BACKGROUND CORPORATE MUSIC ─── */}
      <Audio 
        src={staticFile('audio/bg_music.mp3')} 
        volume={0.10} 
        loop 
      />

      {/* ─── ULTRA-THIN GLOBAL PROGRESS BAR (UDEC CRIMSON) ─── */}
      <div 
        style={{
          position: 'absolute',
          bottom: 0,
          left: 0,
          height: 4,
          width: `${globalProgress * 100}%`,
          backgroundColor: '#E11D48',
          zIndex: 100,
          boxShadow: '0 0 10px rgba(225, 29, 72, 0.8)'
        }}
      />

    </AbsoluteFill>
  );
};

interface ExecutiveActViewProps {
  actData: any;
  config: ActConfig;
}

const ActAudio: React.FC<{ actData: any }> = ({ actData }) => {
  const frame = useCurrentFrame();
  const volume = interpolate(
    frame,
    [0, 15, actData.durationFrames - 15, actData.durationFrames - 5],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );
  return <Audio src={staticFile(actData.audioFile)} volume={volume} />;
};

const ExecutiveActView: React.FC<ExecutiveActViewProps> = ({ actData, config }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const currentSentence = actData.sentences.find(
    (s: any) => frame >= s.startFrame && frame < (s.startFrame + s.durationFrames)
  ) || actData.sentences[actData.sentences.length - 1];

  const actOpacity = interpolate(
    frame,
    [0, 15, actData.durationFrames - 15, actData.durationFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );

  const secondsElapsed = Math.floor(frame / fps);
  const totalSeconds = Math.floor(actData.durationFrames / fps);

  // Transition timings
  const titleEndFade = config.id === 'act1' ? 120 : 60;
  const titleStartFade = config.id === 'act1' ? 100 : 40;
  const platformVideoFadeStart = config.id === 'act1' ? 110 : 30;

  const titleCardOpacity = interpolate(frame, [titleStartFade, titleEndFade], [1, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });

  // Apple-like 3D fly-in
  const entranceProgress = spring({
    frame: frame - platformVideoFadeStart,
    fps,
    config: { damping: 14, mass: 1, stiffness: 60 }
  });

  // Scale slowly increases over time (parallax)
  const dynamicScale = interpolate(frame, [0, actData.durationFrames], [1, 1.05], {
    extrapolateRight: 'clamp'
  });

  const scaleEntrance = interpolate(entranceProgress, [0, 1], [0.95, 1]); 
  
  // Smooth interactive zoom without bounce (Easing.inOut)
  const camProgress = config.cameraMove 
    ? interpolate(frame, [config.cameraMove.startFrame, config.cameraMove.startFrame + 60], [0, 1], {
        extrapolateLeft: 'clamp',
        extrapolateRight: 'clamp',
        easing: Easing.inOut(Easing.cubic)
      })
    : 0;
    
  const camScale = config.cameraMove ? interpolate(camProgress, [0, 1], [1, config.cameraMove.targetScale]) : 1;
  const camX = config.cameraMove ? interpolate(camProgress, [0, 1], [0, config.cameraMove.targetX]) : 0;
  const camY = config.cameraMove ? interpolate(camProgress, [0, 1], [0, config.cameraMove.targetY]) : 0;
  
  const opacityEntrance = interpolate(frame - platformVideoFadeStart, [0, 15], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });

  const finalScale = scaleEntrance * dynamicScale * camScale;

  // Animated glow pulse based on time
  const glowOpacity = interpolate(Math.sin(frame / 15), [-1, 1], [0.1, 0.3]);

  // The Dock entrance
  const dockProgress = spring({
    frame: frame - (platformVideoFadeStart + 15),
    fps,
    config: { damping: 12, mass: 1, stiffness: 80 }
  });
  const dockY = interpolate(dockProgress, [0, 1], [100, 0]);
  const dockOpacity = interpolate(dockProgress, [0, 1], [0, 1]);

  return (
    <AbsoluteFill style={{ 
      opacity: actOpacity,
      // Pure black with a very subtle, elegant glow at the center
      background: 'radial-gradient(circle at 50% 50%, #111827 0%, #000000 70%)', 
      overflow: 'hidden' 
    }}>
      
      {/* ─── LAYER 1: REAL PLATFORM SCREEN RECORDING WITH DYNAMIC ZOOM ─── */}
      <div 
        style={{ 
          position: 'absolute', 
          inset: 0, 
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          opacity: opacityEntrance,
        }}
      >
        <div style={{
          width: '85%',
          height: '75%',
          transform: `scale(${finalScale}) translate(${camX}px, ${camY}px)`,
          transformOrigin: 'center center',
          willChange: 'transform',
          borderRadius: 24, // Subtle rounding
          overflow: 'hidden',
          boxShadow: `0 30px 80px -10px rgba(0, 0, 0, 0.9), 0 0 0 1px rgba(255,255,255,0.1), 0 0 100px rgba(0, 122, 255, ${glowOpacity})`, // Minimal border & elegant animated glow
        }}>
          <OffthreadVideo 
            src={staticFile(config.videoClip)}
            startFrom={config.startFromFrames || 0}
            style={{ 
              width: '100%', 
              height: '100%', 
              objectFit: 'cover',
              objectPosition: 'top center',
            }}
            muted
          />
        </div>
      </div>

      {/* ─── LAYER SFX ─── */}
      {config.sfx && config.sfx.map((s, i) => (
        <Sequence key={`sfx-${i}`} from={s.frame} durationInFrames={30}>
          <Audio src={staticFile(`audio/${s.type}.wav`)} volume={0.6} />
        </Sequence>
      ))}

      {/* ─── UNIFIED EXECUTIVE SUBTITLE DOCK (WWDC Minimalist Pill) ─── */}
      <div 
        style={{
          position: 'absolute',
          bottom: 50,
          left: 0,
          right: 0,
          display: 'flex',
          justifyContent: 'center',
          padding: '0 40px',
          zIndex: 30,
          transform: `translateY(${dockY}px)`,
          opacity: dockOpacity
        }}
      >
        <div 
          style={{
            maxWidth: 900,
            width: '100%',
            backgroundColor: 'rgba(20, 20, 20, 0.65)',
            backdropFilter: 'blur(40px) saturate(150%)',
            WebkitBackdropFilter: 'blur(40px) saturate(150%)',
            borderRadius: 40, // Pill shape
            border: '1px solid rgba(255, 255, 255, 0.1)',
            boxShadow: '0 20px 40px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255,255,255,0.15)',
            padding: '16px 40px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 6
          }}
        >
          {/* Feature Gradient Badge */}
          <span 
            style={{ 
              fontSize: 14, 
              fontWeight: 700, 
              letterSpacing: '0.05em', 
              background: 'linear-gradient(90deg, #F43F5E, #F97316)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              textTransform: 'uppercase' 
            }}
          >
            {config.badgeTitle}
          </span>

          {/* The Current Spoken Sentence */}
          <p 
            style={{ 
              margin: '0', 
              fontSize: 22, 
              fontWeight: 500, 
              color: '#FFFFFF',
              lineHeight: 1.4,
              textAlign: 'center',
              letterSpacing: '-0.01em'
            }}
          >
            {currentSentence?.display || actData.title}
          </p>
        </div>
      </div>

      {/* ─── LAYER 2: INSTITUTIONAL TITLE BUMPER (WWDC Style) ─── */}
      {titleCardOpacity > 0 && (
        <AbsoluteFill 
          style={{
            opacity: titleCardOpacity,
            backgroundColor: '#000000', // Pure black overlay for transitions
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '40px 60px',
            zIndex: 40
          }}
        >
          {config.id === 'act1' ? (
            <div style={{ textAlign: 'center', position: 'relative', width: '100%', height: '100%' }}>
              <div style={{
                position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
                opacity: interpolate(frame, [0, 20, 45, 60], [0, 1, 1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }),
                transform: `scale(${interpolate(frame, [0, 60], [0.95, 1.05])})`
              }}>
                <img 
                  src={staticFile('assets/logo_udec_blanco.png')} 
                  alt="Universidad de Cartagena" 
                  style={{ height: 180, width: 'auto', filter: 'drop-shadow(0px 0px 20px rgba(255,255,255,0.2))' }} 
                />
              </div>
              <div style={{
                position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
                opacity: interpolate(frame, [50, 70, 100, 120], [0, 1, 1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }),
                transform: `scale(${interpolate(frame, [50, 120], [0.98, 1.02])})`
              }}>
                <h1 
                  style={{ 
                    fontSize: 72, 
                    fontWeight: 600, // WWDC bold
                    color: '#FFFFFF', 
                    margin: 0, 
                    lineHeight: 1.1,
                    letterSpacing: '-0.04em', // Tighter tracking like Apple
                    textShadow: '0 0 40px rgba(255,255,255,0.3)' // Subtle glow
                  }}
                >
                  Una universidad a la<br />altura de los tiempos
                </h1>
              </div>
            </div>
          ) : (
            <div style={{ 
              textAlign: 'center', 
              maxWidth: 900, 
              opacity: interpolate(frame, [0, 15, titleStartFade, titleEndFade], [0, 1, 1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }),
              transform: `translateY(${interpolate(frame, [0, 20], [20, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })}) scale(${interpolate(frame, [0, titleEndFade], [0.98, 1.02])})` 
            }}>
              <span style={{ 
                fontSize: 16, 
                fontWeight: 600, 
                letterSpacing: '0.15em', 
                textTransform: 'uppercase', 
                background: 'linear-gradient(90deg, #F43F5E, #F97316)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                display: 'block', 
                marginBottom: 16 
              }}>
                {config.subtitle}
              </span>
              <h1 style={{ 
                fontSize: 64, 
                fontWeight: 700, 
                color: '#FFFFFF', 
                margin: 0, 
                lineHeight: 1.1, 
                letterSpacing: '-0.04em',
                textShadow: '0 0 30px rgba(255,255,255,0.2)'
              }}>
                {config.badgeTitle}
              </h1>
            </div>
          )}
        </AbsoluteFill>
      )}

      {/* ─── LAYER FINAL: INFOGRAPH SUMMARY (ACT 5 ONLY) ─── */}
      {config.id === 'act5' && frame > 480 && (
        <div style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: '#000000', // Flat pure black background
          zIndex: 100,
          opacity: interpolate(frame, [480, 510], [0, 1], { extrapolateRight: 'clamp' })
        }}>
          <div style={{
            padding: '60px',
            width: '100%',
            maxWidth: '1200px',
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: '60px',
            transform: `translateY(${interpolate(frame, [480, 520], [30, 0], { extrapolateRight: 'clamp' })}px)`,
            opacity: interpolate(frame, [490, 530], [0, 1], { extrapolateRight: 'clamp' })
          }}>
            <div style={{ gridColumn: '1 / -1', textAlign: 'center', marginBottom: '40px' }}>
              <img 
                src={staticFile('assets/logo_udec_blanco.png')} 
                alt="UdeC" 
                style={{ height: 100, margin: '0 auto 30px auto', opacity: 0.8 }} 
              />
              <h1 style={{
                fontSize: '56px', fontWeight: 600, margin: 0,
                color: '#fff',
                letterSpacing: '-0.02em'
              }}>
                Educación Continua FCE
              </h1>
              <p style={{ color: '#a1a1aa', fontSize: '24px', marginTop: '16px', fontWeight: 400 }}>La nueva era de formación ejecutiva</p>
            </div>
            
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '56px', fontWeight: 600, color: '#fff' }}>124</div>
              <div style={{ color: '#a1a1aa', fontSize: '20px', marginTop: '8px' }}>Módulos Ejecutivos</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '56px', fontWeight: 600, color: '#F43F5E' }}>100%</div>
              <div style={{ color: '#a1a1aa', fontSize: '20px', marginTop: '8px' }}>Inscripción Digital</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '56px', fontWeight: 600, color: '#F97316' }}>B2B</div>
              <div style={{ color: '#a1a1aa', fontSize: '20px', marginTop: '8px' }}>Portal Corporativo</div>
            </div>
          </div>
        </div>
      )}

    </AbsoluteFill>
  );
};
