import { 
  AbsoluteFill, 
  Sequence, 
  Audio, 
  Img, 
  staticFile, 
  useCurrentFrame, 
  interpolate, 
  useVideoConfig,
  spring
} from 'remotion';

// Import timing manifest generated by Gemini 3.8 Flash TTS
import timings from '../public/audio/voice_timings.json';

interface ActConfig {
  id: string;
  actNumber: string;
  badgeTitle: string;
  subtitle: string;
  imageFile: string;
  audioFile: string;
  cameraMove?: {
    startFrame: number;
    targetScale: number;
    targetX: number;
    targetY: number; // For the container
    scrollY?: number; // For the image scroll inside the container
  };
}

const ACT_CONFIGS: Record<string, ActConfig> = {
  act1: {
    id: 'act1',
    actNumber: '01',
    badgeTitle: 'Apertura Institucional',
    subtitle: 'La Evolución de la Educación Continua',
    imageFile: 'assets/screen_hero.png',
    audioFile: 'audio/posgrados_act1.mp3',
    cameraMove: { startFrame: 200, targetScale: 1.1, targetX: 0, targetY: 0, scrollY: 10 },
  },
  act2: {
    id: 'act2',
    actNumber: '02',
    badgeTitle: 'Catálogo Dinámico',
    subtitle: '124 Cursos Modulares en Tiempo Real',
    imageFile: 'assets/screen_catalog.png',
    audioFile: 'audio/posgrados_act2.mp3',
    cameraMove: { startFrame: 150, targetScale: 1.05, targetX: 0, targetY: 0, scrollY: 30 }, // scroll down the catalog
  },
  act3: {
    id: 'act3',
    actNumber: '03',
    badgeTitle: 'Ficha Técnica e Interactividad',
    subtitle: 'Navegación Intuitiva y Detallada',
    imageFile: 'assets/screen_course_tabs.png',
    audioFile: 'audio/posgrados_act3.mp3',
    cameraMove: { startFrame: 120, targetScale: 1.15, targetX: 0, targetY: 0, scrollY: 15 },
  },
  act4: {
    id: 'act4',
    actNumber: '04',
    badgeTitle: 'Pasarela de Pagos Inmediata',
    subtitle: 'Integración Webhook Menor a 2 Segundos',
    imageFile: 'assets/screen_checkout_pse.png',
    audioFile: 'audio/posgrados_act4.mp3',
    cameraMove: { startFrame: 100, targetScale: 1.2, targetX: 0, targetY: 0, scrollY: 20 },
  },
  act5: {
    id: 'act5',
    actNumber: '05',
    badgeTitle: 'UdeC Empresas B2B',
    subtitle: 'Bolsas de Crédito y Portal Corporativo',
    imageFile: 'assets/screen_empresas_dashboard.png',
    audioFile: 'audio/posgrados_act5.mp3',
    cameraMove: { startFrame: 130, targetScale: 1.15, targetX: 0, targetY: 0, scrollY: 25 },
  }
};

export const VideoInstitucionalPosgrados: React.FC = () => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  // Global presentation progress (0 to 1)
  const globalProgress = interpolate(frame, [0, durationInFrames], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });

  return (
    <AbsoluteFill style={{ backgroundColor: '#000000' }}>
      {timings.acts.map((actData: any) => {
        const config = ACT_CONFIGS[actData.id];
        return (
          <Sequence 
            key={actData.id} 
            from={actData.startFrameGlobal} 
            durationInFrames={actData.durationFrames}
          >
            <ExecutiveActView 
              actData={actData} 
              config={config} 
            />
            <ActAudio actData={actData} />
          </Sequence>
        );
      })}

      {/* ─── BACKGROUND CORPORATE MUSIC ─── */}
      <Audio 
        src={staticFile('audio/bg_music.mp3')} 
        volume={0.06} 
        loop 
      />

      {/* ─── ULTRA-THIN GLOBAL PROGRESS BAR (UDEC CRIMSON) ─── */}
      <div 
        style={{
          position: 'absolute',
          bottom: 0,
          left: 0,
          height: 4,
          width: `${globalProgress * 100}%`,
          backgroundColor: '#E11D48',
          zIndex: 100,
          boxShadow: '0 0 10px rgba(225, 29, 72, 0.8)'
        }}
      />

    </AbsoluteFill>
  );
};

interface ExecutiveActViewProps {
  actData: any;
  config: ActConfig;
}

const ActAudio: React.FC<{ actData: any }> = ({ actData }) => {
  const frame = useCurrentFrame();
  const volume = interpolate(
    frame,
    [0, 15, actData.durationFrames - 15, actData.durationFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );
  const audioFile = ACT_CONFIGS[actData.id].audioFile;
  return <Audio src={staticFile(audioFile)} volume={volume} />;
};

const ExecutiveActView: React.FC<ExecutiveActViewProps> = ({ actData, config }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const currentSentence = actData.sentences.find(
    (s: any) => frame >= s.startFrame && frame < (s.startFrame + s.durationFrames)
  ) || actData.sentences[actData.sentences.length - 1];

  const actOpacity = interpolate(
    frame,
    [0, 15, actData.durationFrames - 15, actData.durationFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );

  const titleStartFade = 120;
  const titleEndFade = 150;
  const platformVideoFadeStart = 160;

  const entranceProgress = spring({
    frame: frame - platformVideoFadeStart,
    fps,
    config: { damping: 14, mass: 1, stiffness: 60 }
  });

  // Scale slowly increases over time (parallax)
  const dynamicScale = interpolate(frame, [0, actData.durationFrames], [1, 1.05], {
    extrapolateRight: 'clamp'
  });

  // Apply spring to 3D transforms with Apple-style smooth damping
  const rotateX = interpolate(entranceProgress, [0, 1], [25, 0]); // Softer tilt
  const rotateY = interpolate(entranceProgress, [0, 1], [-10, 0]); 
  const scaleEntrance = interpolate(entranceProgress, [0, 1], [0.8, 1]); 
  
  const opacityEntrance = interpolate(frame - platformVideoFadeStart, [0, 15], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });

  // Dynamic Camera Pan / Zoom
  let panX = 0;
  let panY = 0;
  let panScale = 1;
  let innerScrollY = 0; // The actual webpage scroll inside the window

  if (config.cameraMove) {
    const panProgress = spring({
      frame: frame - config.cameraMove.startFrame,
      fps,
      config: { damping: 20, mass: 1.2, stiffness: 45 } // Smoother, heavier spring (Apple style)
    });
    panScale = interpolate(panProgress, [0, 1], [1, config.cameraMove.targetScale]);
    panX = interpolate(panProgress, [0, 1], [0, config.cameraMove.targetX]);
    panY = interpolate(panProgress, [0, 1], [0, config.cameraMove.targetY]);
    if (config.cameraMove.scrollY) {
      innerScrollY = interpolate(panProgress, [0, 1], [0, config.cameraMove.scrollY]);
    }
  }

  const finalScale = scaleEntrance * dynamicScale * panScale;

  // The Dock entrance
  const dockProgress = spring({
    frame: frame - (platformVideoFadeStart + 15),
    fps,
    config: { damping: 12, mass: 1, stiffness: 80 }
  });
  const dockY = interpolate(dockProgress, [0, 1], [100, 0]);
  const dockOpacity = interpolate(dockProgress, [0, 1], [0, 1]);

  return (
    <AbsoluteFill style={{ 
      opacity: actOpacity,
      // Pure black with a very subtle, elegant glow at the center
      background: 'radial-gradient(circle at 50% 50%, #111827 0%, #000000 70%)', 
      overflow: 'hidden' 
    }}>
      
      {/* ─── LAYER 1: HIGH RES SCREENSHOT WITH DYNAMIC 3D ZOOM ─── */}
      <div 
        style={{ 
          position: 'absolute', 
          inset: 0, 
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          perspective: 2000, // Deeper perspective for a flatter, more cinematic 3D
          opacity: opacityEntrance,
        }}
      >
        <div style={{
          width: '80%',
          height: '70%',
          transform: `scale(${finalScale}) translateX(${panX}%) translateY(${panY}%) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`,
          transformOrigin: 'center center',
          willChange: 'transform',
          borderRadius: 32, // More rounded, modern corners
          overflow: 'hidden',
          boxShadow: '0 50px 120px -20px rgba(0, 0, 0, 1), 0 0 0 1px rgba(255,255,255,0.15)', // Premium Apple border & shadow
          position: 'relative',
          backgroundColor: '#FFFFFF' // Base color for screenshots
        }}>
          {/* THE ACTUAL WEBPAGE CONTENT */}
          <Img 
            src={staticFile(config.imageFile)}
            style={{ 
              width: '100%',
              height: 'auto', 
              position: 'absolute',
              top: 0,
              left: 0,
              transform: `translateY(-${innerScrollY}%)`, // Simulate Scrolling!
            }}
          />
        </div>
      </div>

      {/* ─── UNIFIED EXECUTIVE SUBTITLE DOCK (WWDC Minimalist Pill) ─── */}
      <div 
        style={{
          position: 'absolute',
          bottom: 50,
          left: 0,
          right: 0,
          display: 'flex',
          justifyContent: 'center',
          padding: '0 40px',
          zIndex: 30,
          transform: `translateY(${dockY}px)`,
          opacity: dockOpacity
        }}
      >
        <div 
          style={{
            maxWidth: 900,
            width: '100%',
            backgroundColor: 'rgba(20, 20, 20, 0.65)',
            backdropFilter: 'blur(40px) saturate(150%)',
            WebkitBackdropFilter: 'blur(40px) saturate(150%)',
            borderRadius: 40, // Pill shape
            border: '1px solid rgba(255, 255, 255, 0.1)',
            boxShadow: '0 20px 40px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255,255,255,0.15)',
            padding: '16px 40px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 6
          }}
        >
          {/* Feature Gradient Badge */}
          <span 
            style={{ 
              fontSize: 14, 
              fontWeight: 700, 
              letterSpacing: '0.05em', 
              background: 'linear-gradient(90deg, #F43F5E, #F97316)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              textTransform: 'uppercase' 
            }}
          >
            {config.badgeTitle}
          </span>

          {/* The Current Spoken Sentence */}
          <p 
            style={{ 
              margin: '0', 
              fontSize: 22, 
              fontWeight: 500, 
              color: '#FFFFFF',
              lineHeight: 1.4,
              textAlign: 'center',
              letterSpacing: '-0.01em'
            }}
          >
            {currentSentence?.display || actData.title}
          </p>
        </div>
      </div>

      {/* ─── LAYER 3: CINEMATIC TITLE SEQUENCE ─── */}
      {frame < titleEndFade && (
        <AbsoluteFill style={{ 
          alignItems: 'center', 
          justifyContent: 'center', 
          backgroundColor: '#000000',
          zIndex: 50,
          opacity: interpolate(frame, [titleStartFade, titleEndFade], [1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })
        }}>
          {config.id === 'act1' ? (
            <div style={{ position: 'relative', width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <div style={{
                position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
                opacity: interpolate(frame, [0, 20, 50, 70], [0, 1, 1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }),
                transform: `scale(${interpolate(frame, [0, 60], [0.95, 1.05])})`
              }}>
                <Img 
                  src={staticFile('assets/logo_udec_blanco.png')} 
                  alt="Universidad de Cartagena" 
                  style={{ height: 180, width: 'auto', filter: 'drop-shadow(0px 0px 20px rgba(255,255,255,0.2))' }} 
                />
              </div>
              <div style={{
                position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
                opacity: interpolate(frame, [50, 70, 100, 120], [0, 1, 1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }),
                transform: `scale(${interpolate(frame, [50, 120], [0.98, 1.02])})`
              }}>
                <h1 
                  style={{ 
                    fontSize: 72, 
                    fontWeight: 600, // WWDC bold
                    color: '#FFFFFF', 
                    margin: 0, 
                    lineHeight: 1.1,
                    letterSpacing: '-0.04em', // Tighter tracking like Apple
                    textShadow: '0 0 40px rgba(255,255,255,0.3)' // Subtle glow
                  }}
                >
                  Una universidad a la<br />altura de los tiempos
                </h1>
              </div>
            </div>
          ) : (
            <div style={{ 
              textAlign: 'center', 
              maxWidth: 900, 
              opacity: interpolate(frame, [0, 15, titleStartFade, titleEndFade], [0, 1, 1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }),
              transform: `translateY(${interpolate(frame, [0, 20], [20, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })}) scale(${interpolate(frame, [0, titleEndFade], [0.98, 1.02])})` 
            }}>
              <span style={{ 
                fontSize: 16, 
                fontWeight: 600, 
                letterSpacing: '0.15em', 
                textTransform: 'uppercase', 
                background: 'linear-gradient(90deg, #F43F5E, #F97316)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                display: 'block', 
                marginBottom: 16 
              }}>
                {config.subtitle}
              </span>
              <h1 style={{ 
                fontSize: 64, 
                fontWeight: 700, 
                color: '#FFFFFF', 
                margin: 0, 
                lineHeight: 1.1, 
                letterSpacing: '-0.04em',
                textShadow: '0 0 30px rgba(255,255,255,0.2)'
              }}>
                {config.badgeTitle}
              </h1>
            </div>
          )}
        </AbsoluteFill>
      )}

      {/* ─── LAYER FINAL: INFOGRAPH SUMMARY (ACT 5 ONLY) ─── */}
      {config.id === 'act5' && frame > 480 && (
        <div style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: '#000000', // Solid black background, NOT semi-transparent
          zIndex: 80,
          opacity: interpolate(frame, [480, 510], [0, 1]),
        }}>
          <Img 
            src={staticFile('assets/logo_udec_blanco.png')} 
            style={{ 
              height: 100, 
              marginBottom: 40,
              filter: 'drop-shadow(0 0 20px rgba(255,255,255,0.2))'
            }} 
          />
          <h2 style={{ 
            color: 'white', 
            fontSize: 56, 
            fontWeight: 700, 
            margin: 0, 
            letterSpacing: '-0.02em',
            textAlign: 'center'
          }}>
            Facultad de Ciencias Económicas
          </h2>
          <p style={{ 
            color: '#A1A1AA', 
            fontSize: 28, 
            marginTop: 16, 
            fontWeight: 400 
          }}>
            Educación Continua de Clase Mundial
          </p>
          
          <div style={{
            display: 'flex',
            gap: 40,
            marginTop: 60,
          }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: 48, fontWeight: 800, color: '#F43F5E' }}>124</div>
              <div style={{ color: '#D4D4D8', fontSize: 18, textTransform: 'uppercase', letterSpacing: '0.1em', marginTop: 8 }}>Módulos<br/>Ejecutivos</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: 48, fontWeight: 800, color: '#F97316' }}>100%</div>
              <div style={{ color: '#D4D4D8', fontSize: 18, textTransform: 'uppercase', letterSpacing: '0.1em', marginTop: 8 }}>Integración<br/>Digital</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: 48, fontWeight: 800, color: '#F43F5E' }}>24/7</div>
              <div style={{ color: '#D4D4D8', fontSize: 18, textTransform: 'uppercase', letterSpacing: '0.1em', marginTop: 8 }}>Disponibilidad<br/>Global</div>
            </div>
          </div>
        </div>
      )}

    </AbsoluteFill>
  );
};
